### PR TITLE
Gemfiles update - rails 4.2.7.1, devise, uglifier

### PR DESCRIPTION
**Pull request by ying-pbrc**

### CODE REVIEW

**Comment by jleonardw9** [comment]
Hey Ying. Sorry, we were supposed to message you on this weeks ago but it fell through the cracks. We tried rerunning this on Travis a few times and could not get it to pass. Can you please merge in the latest code and try to get this passing? We will merge it in as soon as you do.

**Comment by ying-pbrc** [comment]
Sure. Will do.

**Comment by jleonardw9** [comment]
It looks like there is still one failing spec. I looked at it and it's not related to anything you did, so I'm just going to merge it in and fix it myself. Thanks for the work!

**Comment by ying-pbrc** [comment]
sorry, i didn't see your latest response before sending out email to Wenjun. I did get a few failures this when i ran tests this morning and was trying to fix it. You can probably fix it much quicker than i do. Thanks!

**Pull request merged**
