### PR TITLE
KG - Study Schedule Visits Overflow Issue

### PR DESCRIPTION
**Pull request by kyle-glick**

### CODE REVIEW

**Comment by ctt3** [comment]
8 shouldn't be hard-coded. it should come from Visit.per_page

**Comment by kyle-glick** [comment]
Ah, thank you Charlie

**Comment by amcates** [comment]
so, is this pull request needed?  or was it done wrong?

**Comment by kyle-glick** [comment]
The per_page delimiter limits the visit groups rendered to the page to 8, whereas before every visit group box was showing up for the SPARC line_items_visits

**Comment by kyle-glick** [comment]
For some reason, the paginate was not correctly dividing these up before

**Pull request merged**
