### PR TITLE
added epic option and made visit_group.day vaildation conditional

### PR DESCRIPTION
**Pull request by ying-pbrc**
replacing previous pull request #66

### CODE REVIEW

**Comment by amcates** [comment]
Can you write specs for this?  I'm not sure the :unless is working like it should.

**Comment by ying-pbrc** [comment]
Will do.

I was using the standard way of ‘unless/if’ initially, but it didn’t work. Then found this article:
http://guides.rubyonrails.org/active_record_validations.html#conditional-validation

With one line code, either of the following validates that the day attribute is present unless the variable USE_EPIC is set to false in .env.

validates :day, presence: true, unless: "ENV.fetch('USE_EPIC'){nil} == 'false'"

validates :day, presence: true, if: "ENV.fetch('USE_EPIC'){true} == ‘true’"

**Comment by sparc-request** [comment]
Ok, I wasn’t aware that it would use eval on a string.  Should work but I think specs should still be included.

Andrew Cates
Ruby Development Manager
Biomedical Informatics Center
Medical University of South Carolina

**Comment by robertjamesmiller** [comment]
We may have a second issue in the protocol importer. If the following line of code returns “true” when a sister/brother service is per patient then we’re processing ARMs unnecessarily for services that are one_time_fee=true, correct? 
if fulfillment_protocol.organization.inclusive_child_services(:per_participant).present?

**Comment by ying-pbrc** [comment]
I updated this pull request to include the specs in app/models/visit_group_spec.rb. Please review, thanks.

**Pull request merged**
