### PR TITLE
Added developer notes to README and documented header customization option

### PR DESCRIPTION
**Pull request by robertjamesmiller**

### CODE REVIEW

**Comment by ctt3** [comment]
Can we gitignore customize.sass?

**Comment by robertjamesmiller** [comment]
I don’t think so because then you’d have to remove the @import statement at the bottom of application.sass and we don’t want other institutions to have to maintain their own copy of that file too.

**Comment by sparc-request** [comment]
I only worry about people committing that file.  If you make local changes it would be easy to forget and do a pull request.    Would it make sense to make it configurable in the .env file and then just included in the appropriate layouts?

Andrew Cates
Ruby Development Manager
Biomedical Informatics Center
Medical University of South Carolina

**Comment by robertjamesmiller** [comment]
That sounds good. Do you want me to make that change? Or, will you all?

**Pull request merged**
