### PR TITLE
Shibboleth integration

### PR DESCRIPTION
**Pull request by robertjamesmiller**

### CODE REVIEW

**Comment by ctt3** [comment]
Can this be configured so that Shibboleth can be turned off?

**Comment by robertjamesmiller** [comment]
Configuration to make Shibboleth optional can be added to this pull request but I wasn't sure how you wanted to handle it. We're planning to only use Shibboleth. Will MUSC allow their users multiple login options (e.g., Shibboleth, LDAP, database)? Or, are you planning to discontinue LDAP when you turn on Shibboleth?

**Comment by sparc-request** [comment]
I think we would prefer it be configurable.  As an OS product we want to support as many authentication schemes as possible.

Andrew Cates
Ruby Development Manager
Biomedical Informatics Center
Medical University of South Carolina

**Comment by robertjamesmiller** [comment]
Ok, I'll update routes.rb to be configurable and let you know when that has been done.

**Comment by robertjamesmiller** [comment]
@amcates I updated our pull request to make Shibboleth configurable. Since we'll use only Shibboleth I'm hoping it is okay that you all will update /app/views/devise/sessions/new.html.haml to include a "MUSC Users" click here button that will send your users to your Shibboleth login. How does that sound?

**Comment by robertjamesmiller** [comment]
This branch now has merge conflicts. Please let me know in advance when you're getting ready to merge it and I'll quickly resolve the conflicts.

**Comment by amcates** [comment]
If you resolve it now, I will go a head and merge it.  Sorry, we are going over pull requests today.

**Comment by robertjamesmiller** [comment]
I resolved it, thanks.

**Pull request merged**
