### PR TITLE
Hide task & report notifications (red circles) when values are zero

### PR DESCRIPTION
**Pull request by robertjamesmiller**
In the navigation, we want to give the red circles a greater emphasis by hiding them when their values are zero.

### CODE REVIEW

**Comment by kyle-glick** [comment]
A few things
1. There should be 3 red circles. A circle for tasks, a circle for the All Reports page, and a circle for the Reports tab within a protocol.
2. This would only account for the default rendering of the page. There is Javascript that deals with the incrementing/decrementing of these that would need to be altered to hide the elements as well as the HTML.

**Comment by robertjamesmiller** [comment]
Regarding 1), I can update the "circle for the Reports tab within a protocol" or leave as is for now, that one is not as prevalent, what's your preference?
Regarding 2), I prefer to leave the JavaScript as is for now since the JavaScript doesn't automatically update the # when a report is added. And, it's not a big deal to us for a zero to be displayed there temporarily.
Regarding 3), I'll take a look at the specs and see what I can do.

**Comment by kyle-glick** [comment]
Regarding 1), personally I would apply the change to all 3 counters for consistency
Regarding 2), their is Javascript that automatically update the counters (see "update_view_on_download_new_report" in app/assets/javascripts/documents.js.coffee and app/views/tasks/update.js.coffee)

**Comment by robertjamesmiller** [comment]
Gotcha, sounds good, and am working on it now.

**Comment by robertjamesmiller** [comment]
@kyle-glick I think I got everything straightened out. Please review and let me know if anything else needs to be done, thanks.

**Comment by kyle-glick** [comment]
@robertjamesmiller A few things,
1. Can you move the HTML in-line logic to a view helper?
2. Can you add a test case in the reports specs that you modified for both decrementing (such as 2 -> 1) and hiding the bubble (1 -> hidden)?

Thanks!

**Comment by robertjamesmiller** [comment]
Sure. do you mean replace this with a method: @protocol.unaccessed_documents_count > 0 ; or something else?

**Comment by robertjamesmiller** [comment]
Hiding the bubble (1 -> hidden) should already be tested with the have_no_css and I'll look into adding the 2 -> 1

**Comment by kyle-glick** [comment]
Things like this:

- if current_identity.tasks_count > 0     
    %span.notification.task-notifications
    = current_identity.tasks_count

in "app/views/application/_nav.html.haml" and "app/views/protocols/show.html.haml"

**Comment by robertjamesmiller** [comment]
@kyle-glick I added tests for 2 -> 1 scenarios. I didn't move anything into a view helper because it didn't seem like a good idea to put HTML into Ruby and there's no code duplication to be optimized. I need to work on other features but feel free to modify this pull request as you see fit, thanks.

**Comment by amcates** [comment]
@robertjamesmiller I agree, moving the code to a helper in this example won't save much in the way of cleaning up the code.  It will actually add more to it.  If there was more logic I would argue that a helper method would be better.

**Pull request merged**
